//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdfandmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrt
    {
        public int Fahrt_ID { get; set; }
        public string Abholort { get; set; }
        public string Abgabeort { get; set; }
        public Nullable<System.DateTime> Startzeit { get; set; }
        public Nullable<System.DateTime> Endzeit { get; set; }
        public Nullable<double> Start_KM { get; set; }
        public Nullable<double> End_KM { get; set; }
        public Nullable<int> Car_ID { get; set; }
        public Nullable<int> Kunde_ID { get; set; }
        public Nullable<int> Reservierung_ID { get; set; }
    
        public virtual Kunde Kunde { get; set; }
    }
}
