//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdfandmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        public Kunde()
        {
            this.Rechnung = new HashSet<Rechnung>();
            this.Fahrt = new HashSet<Fahrt>();
        }
    
        public int Kunde_ID { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public int Adress_ID { get; set; }
        public Nullable<int> RechnungAdr_ID { get; set; }
        public int Bank_ID { get; set; }
        public bool Gesperrt { get; set; }
        public string Email { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Kunde Kunde1 { get; set; }
        public virtual Kunde Kunde2 { get; set; }
        public virtual ICollection<Rechnung> Rechnung { get; set; }
        public virtual ICollection<Fahrt> Fahrt { get; set; }
    }
}
